# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/diktyoncuba/public/tree/main/Informes"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter/X"
    url        = "https://x.com/DiktyonCuba"

    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/DiktyonCuba"

    [social.params]
        icon = "X"

[[social]]
    identifier = "facebook"
    name       = "Facebook"
    url        = "https://www.facebook.com/DiktyonCuba/"

    [social.params]
        icon = "Telegram_black"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/DiktyonCuba/"

    [social.params]
        icon = "facebook-brand"
        
