# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# Para mas iconos buscar en: https://github.com/tabler/tabler-icons/tree/main/icons
[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/diktyoncuba/public/tree/main/Informes"

    [social.params]
        icon = "brand-github"

#[[social]]
#    identifier = "twitter"
#    name       = "Twitter/X"
#    url        = "https://x.com/DiktyonCuba"

#    [social.params]
#        icon = "brand-twitter"

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/DiktyonCuba"

    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "facebook"
    name       = "Facebook"
    url        = "https://www.facebook.com/DiktyonCuba/"

    [social.params]
        icon = "brand-facebook"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/DiktyonCuba/"

    [social.params]
        icon = "brand-instagram"
        
[[social]]
    identifier = "telegram"
    name       = "Telegram"
    url        = "https://www.telegram.org/DiktyonCuba/"

    [social.params]
        icon = "brand-telegram"
        
